# omakit completion for bash. Generated by `omakit completion bash` from
# marketplace pin 38060f89d2a10b1f9b6b5afe8e226451e8a5b3f6; the categories and tags
# below are that pin's submission form. Regenerate it by running the command
# again.

_omakit() {
  local cur prev command
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}
  local commands='setup pin submit watch verify help upgrade doctor completion parity'
  local categories='Appearance
Desktop
Developer Tools
Hardware
Kids
Productivity
System
Widgets
Other'
  local tags='ai bar education games hyprland kids launcher media power-management quickshell security system workspaces'
  local shells='bash zsh fish'
  COMPREPLY=()
  if ((COMP_CWORD == 1)); then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi
  command=${COMP_WORDS[1]}
  case "$command" in
  setup)
    ;;
  pin)
    ;;
  submit)
    case "$prev" in
    --category) _omakit_values "$categories" "$cur"; return ;;
    --tags) _omakit_list "$tags" "$cur"; return ;;
    --notes) return ;;
    --suggest-tag) return ;;
    --name) return ;;
    --out) COMPREPLY=($(compgen -f -- "$cur")); compopt -o filenames 2>/dev/null; return ;;
    esac
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--category --tags --notes --suggest-tag --name --offline --allow-dirty --json --out' -- "$cur"))
      return
    fi
    COMPREPLY=($(compgen -d -- "$cur"))
    compopt -o filenames 2>/dev/null
    ;;
  watch)
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--json' -- "$cur"))
      return
    fi
    ;;
  verify)
    case "$prev" in
    --out) COMPREPLY=($(compgen -f -- "$cur")); compopt -o filenames 2>/dev/null; return ;;
    esac
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--allow-dirty --out' -- "$cur"))
      return
    fi
    COMPREPLY=($(compgen -d -- "$cur"))
    compopt -o filenames 2>/dev/null
    ;;
  help)
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--agent' -- "$cur"))
      return
    fi
    ;;
  upgrade)
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--dry-run' -- "$cur"))
      return
    fi
    ;;
  doctor)
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--offline --json' -- "$cur"))
      return
    fi
    ;;
  completion)
    ((COMP_CWORD == 2)) && COMPREPLY=($(compgen -W "$shells" -- "$cur"))
    ;;
  parity)
    case "$prev" in
    --count) return ;;
    --offset) return ;;
    --out) COMPREPLY=($(compgen -f -- "$cur")); compopt -o filenames 2>/dev/null; return ;;
    esac
    if [[ "$cur" == -* ]]; then
      COMPREPLY=($(compgen -W '--count --offset --out' -- "$cur"))
      return
    fi
    ;;
  esac
}

# A controlled value may contain a space, so each match is one line and is
# escaped on the way out, the way the shell would have to type it.
_omakit_values() {
  local IFS=$'\n' i
  COMPREPLY=($(compgen -W "$1" -- "${2//\\ / }"))
  for i in "${!COMPREPLY[@]}"; do COMPREPLY[i]=$(printf '%q' "${COMPREPLY[i]}"); done
}

# A comma-separated list: complete the segment after the last comma and keep
# what came before it.
_omakit_list() {
  local prefix="" part="$2"
  if [[ "$2" == *,* ]]; then prefix="${2%,*},"; part="${2##*,}"; fi
  COMPREPLY=($(compgen -P "$prefix" -W "$1" -- "$part"))
}

complete -F _omakit omakit
