# omakit completion for fish. Generated by `omakit completion fish` from
# marketplace pin 38060f89d2a10b1f9b6b5afe8e226451e8a5b3f6; the categories and tags
# below are that pin's submission form. Regenerate it by running the command
# again.

complete -c omakit -f
complete -c omakit -n __fish_use_subcommand -a setup -d 'First run, in one command: check the environment, fetch the pinned marketplace checkout, and say what to try first.'
complete -c omakit -n __fish_use_subcommand -a pin -d 'Fetch or verify the pinned marketplace checkout in the user cache: $XDG_CACHE_HOME/omakit/marketplace, or ~/.cache/omakit/marketplace.'
complete -c omakit -n __fish_use_subcommand -a submit -d 'Every check that is knowable before submitting, the resolved commit, and the exact issue title and body.'
complete -c omakit -n __fish_use_subcommand -a watch -d 'Compare the commit the marketplace validated on a submission issue with the plugin repository'\''s current default-branch HEAD, and say what makes it validate a newer one.'
complete -c omakit -n __fish_use_subcommand -a verify -d 'The official marketplace security baseline over the local Git transport, reported verbatim beside the pin identity.'
complete -c omakit -n __fish_use_subcommand -a help -d 'The operating instructions for a coding agent, printed from skills/, so an agent can read the contract out of the tool instead of the repository.'
complete -c omakit -n __fish_use_subcommand -a upgrade -d 'Fast-forward this checkout of omakit itself.'
complete -c omakit -n __fish_use_subcommand -a doctor -d 'What is installed, what is pinned, and what has moved since.'
complete -c omakit -n __fish_use_subcommand -a completion -d 'The completion script omakit setup installs for your shell, printed for another one.'
complete -c omakit -n __fish_use_subcommand -a parity -d 'The official baseline over GitHub versus the local transport on real listed repositories; a packaged install requires --out for evidence.'
complete -c omakit -n '__fish_seen_subcommand_from submit' -a '(__fish_complete_directories)'
complete -c omakit -n '__fish_seen_subcommand_from submit' -l category -x -a 'Appearance Desktop Developer\ Tools Hardware Kids Productivity System Widgets Other'
complete -c omakit -n '__fish_seen_subcommand_from submit' -l tags -x -a 'ai bar education games hyprland kids launcher media power-management quickshell security system workspaces'
complete -c omakit -n '__fish_seen_subcommand_from submit' -l notes -x
complete -c omakit -n '__fish_seen_subcommand_from submit' -l suggest-tag -x
complete -c omakit -n '__fish_seen_subcommand_from submit' -l name -x
complete -c omakit -n '__fish_seen_subcommand_from submit' -l offline
complete -c omakit -n '__fish_seen_subcommand_from submit' -l allow-dirty
complete -c omakit -n '__fish_seen_subcommand_from submit' -l json
complete -c omakit -n '__fish_seen_subcommand_from submit' -l out -r
complete -c omakit -n '__fish_seen_subcommand_from watch' -l json
complete -c omakit -n '__fish_seen_subcommand_from verify' -a '(__fish_complete_directories)'
complete -c omakit -n '__fish_seen_subcommand_from verify' -l allow-dirty
complete -c omakit -n '__fish_seen_subcommand_from verify' -l out -r
complete -c omakit -n '__fish_seen_subcommand_from help' -l agent
complete -c omakit -n '__fish_seen_subcommand_from upgrade' -l dry-run
complete -c omakit -n '__fish_seen_subcommand_from doctor' -l offline
complete -c omakit -n '__fish_seen_subcommand_from doctor' -l json
complete -c omakit -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c omakit -n '__fish_seen_subcommand_from parity' -l count -x
complete -c omakit -n '__fish_seen_subcommand_from parity' -l offset -x
complete -c omakit -n '__fish_seen_subcommand_from parity' -l out -r
