// Tab completion for bash, zsh and fish, installed by `omakit setup` for the
// shell it runs from.
//
// Everything the script completes is derived, never retyped: the subcommands
// and their flags from COMMANDS in usage.mjs, so a command added there cannot
// be missing here, and the categories and tags from the submission form at the
// marketplace pin, the same source the checks read. Those controlled values are
// baked into the emitted script rather than fetched on every keypress: node's
// startup plus a pin read is not something to put behind a TAB. The script says
// in its own header which pin it came from and how to regenerate it.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, dirname, join } from "node:path"
import { tagSlug } from "./form.mjs"
import { COMMANDS, COMPLETION_SHELLS } from "./usage.mjs"
import { withHomeAbbreviated } from "./paths.mjs"

/**
 * The completion model, read out of the help data. A subcommand is the word
 * after `omakit` in its signature; a flag is every `--word` in it, valued when
 * a `<placeholder>` follows it; `<target>` in the signature means the first
 * positional is a directory.
 *
 * @param {ReadonlyArray<{ signature: string|string[], lines: string[] }>} commands
 */
export function subcommandsOf(commands = COMMANDS) {
  return commands.map((command) => {
    const signature = [].concat(command.signature).join(" ")
    const name = signature.match(/^omakit +([a-z][a-z-]*)/)?.[1]
    if (!name) throw new Error(`completion: no subcommand in signature ${JSON.stringify(signature)}`)
    const flags = [...signature.matchAll(/(--[a-z][a-z-]*)(?: <([^>]+)>)?/g)].map(([, flag, placeholder]) => ({
      flag,
      value: placeholder ? placeholderKind(placeholder) : null,
    }))
    const sentence = command.lines.join(" ").replace(/`/g, "").split(/(?<=\.)\s/)[0]
    return { name, description: sentence, flags, target: /<target>/.test(signature) }
  })
}

/** What a valued flag takes, by its placeholder: a controlled value, a file, or free text. */
function placeholderKind(placeholder) {
  if (placeholder === "c") return "category"
  if (placeholder === "a,b") return "tags"
  if (placeholder === "file") return "file"
  return "text"
}

/**
 * @param {"bash"|"zsh"|"fish"} shell
 * @param {{ contract: { categories: string[], tagLabels: string[] }, pin: string, commands?: typeof COMMANDS }} options
 * @returns {string} the script
 */
export function renderCompletion(shell, { contract, pin, commands = COMMANDS }) {
  if (!COMPLETION_SHELLS.includes(shell)) throw new Error(`completion: no script for ${shell}`)
  const model = {
    subcommands: subcommandsOf(commands),
    categories: [...contract.categories],
    tags: contract.tagLabels.map(tagSlug),
    pin,
  }
  return { bash, zsh, fish }[shell](model)
}

function header(comment, shell, pin) {
  return [
    `${comment} omakit completion for ${shell}. Generated by \`omakit setup\` from`,
    `${comment} marketplace pin ${pin}; the categories and tags`,
    `${comment} below are that pin's submission form. Regenerate it by running setup`,
    `${comment} again.`,
  ]
}

const single = (text) => `'${String(text).replace(/'/g, "'\\''")}'`

// --- bash ---------------------------------------------------------------------

function bash({ subcommands, categories, tags, pin }) {
  const lines = [...header("#", "bash", pin), ""]
  lines.push("_omakit() {")
  lines.push("  local cur prev command")
  lines.push("  cur=${COMP_WORDS[COMP_CWORD]}")
  lines.push("  prev=${COMP_WORDS[COMP_CWORD-1]}")
  lines.push(`  local commands=${single(subcommands.map((c) => c.name).join(" "))}`)
  lines.push(`  local categories=${single(categories.join("\n"))}`)
  lines.push(`  local tags=${single(tags.join(" "))}`)
  lines.push("  COMPREPLY=()")
  lines.push("  if ((COMP_CWORD == 1)); then")
  lines.push('    COMPREPLY=($(compgen -W "$commands" -- "$cur"))')
  lines.push("    return")
  lines.push("  fi")
  lines.push("  command=${COMP_WORDS[1]}")
  lines.push('  case "$command" in')
  for (const sub of subcommands) {
    lines.push(`  ${sub.name})`)
    const valued = sub.flags.filter((f) => f.value)
    if (valued.length) {
      lines.push('    case "$prev" in')
      for (const { flag, value } of valued) {
        if (value === "category") lines.push(`    ${flag}) _omakit_values "$categories" "$cur"; return ;;`)
        else if (value === "tags") lines.push(`    ${flag}) _omakit_list "$tags" "$cur"; return ;;`)
        else if (value === "file") lines.push(`    ${flag}) COMPREPLY=($(compgen -f -- "$cur")); compopt -o filenames 2>/dev/null; return ;;`)
        else lines.push(`    ${flag}) return ;;`)
      }
      lines.push("    esac")
    }
    if (sub.flags.length) {
      lines.push('    if [[ "$cur" == -* ]]; then')
      lines.push(`      COMPREPLY=($(compgen -W ${single(sub.flags.map((f) => f.flag).join(" "))} -- "$cur"))`)
      lines.push("      return")
      lines.push("    fi")
    }
    if (sub.target) {
      lines.push('    COMPREPLY=($(compgen -d -- "$cur"))')
      lines.push("    compopt -o filenames 2>/dev/null")
    }
    lines.push("    ;;")
  }
  lines.push("  esac")
  lines.push("}")
  lines.push("")
  lines.push("# A controlled value may contain a space, so each match is one line and is")
  lines.push("# escaped on the way out, the way the shell would have to type it.")
  lines.push("_omakit_values() {")
  lines.push("  local IFS=$'\\n' i")
  lines.push('  COMPREPLY=($(compgen -W "$1" -- "${2//\\\\ / }"))')
  lines.push('  for i in "${!COMPREPLY[@]}"; do COMPREPLY[i]=$(printf \'%q\' "${COMPREPLY[i]}"); done')
  lines.push("}")
  lines.push("")
  lines.push("# A comma-separated list: complete the segment after the last comma and keep")
  lines.push("# what came before it.")
  lines.push("_omakit_list() {")
  lines.push('  local prefix="" part="$2"')
  lines.push('  if [[ "$2" == *,* ]]; then prefix="${2%,*},"; part="${2##*,}"; fi')
  lines.push('  COMPREPLY=($(compgen -P "$prefix" -W "$1" -- "$part"))')
  lines.push("}")
  lines.push("")
  lines.push("complete -F _omakit omakit")
  return `${lines.join("\n")}\n`
}

// --- zsh ----------------------------------------------------------------------

const zshDescribe = (name, description) => single(`${name}:${description.replace(/:/g, "\\:")}`)

function zsh({ subcommands, categories, tags, pin }) {
  const lines = ["#compdef omakit", ...header("#", "zsh", pin), ""]
  lines.push("_omakit() {")
  lines.push("  local curcontext=\"$curcontext\" state line")
  lines.push("  typeset -A opt_args")
  lines.push("  local -a commands categories tags shells")
  lines.push("  commands=(")
  for (const sub of subcommands) lines.push(`    ${zshDescribe(sub.name, sub.description)}`)
  lines.push("  )")
  lines.push(`  categories=(${categories.map(single).join(" ")})`)
  lines.push(`  tags=(${tags.map(single).join(" ")})`)
  lines.push("  _arguments -C '1:command:->command' '*::arguments:->arguments'")
  lines.push('  case "$state" in')
  lines.push("  command)")
  lines.push("    _describe -t commands 'omakit command' commands")
  lines.push("    ;;")
  lines.push("  arguments)")
  lines.push('    case "$line[1]" in')
  for (const sub of subcommands) {
    lines.push(`    ${sub.name})`)
    const specs = sub.flags.map(({ flag, value }) => {
      if (value === "category") return single(`${flag}:category:{compadd -a categories}`)
      if (value === "tags") return single(`${flag}:tags:{_values -s , tag $tags}`)
      if (value === "file") return single(`${flag}:file:_files`)
      if (value === "text") return single(`${flag}:text:`)
      return single(flag)
    })
    if (sub.target) specs.push(single("1:target:_directories"))
    if (specs.length) lines.push(`      _arguments ${specs.join(" ")}`)
    lines.push("      ;;")
  }
  lines.push("    esac")
  lines.push("    ;;")
  lines.push("  esac")
  lines.push("}")
  lines.push("")
  lines.push('_omakit "$@"')
  return `${lines.join("\n")}\n`
}

// --- fish ---------------------------------------------------------------------

const fishWord = (text) => String(text).replace(/([\\'" ])/g, "\\$1")

function fish({ subcommands, categories, tags, pin }) {
  const lines = [...header("#", "fish", pin), ""]
  lines.push("complete -c omakit -f")
  for (const sub of subcommands) {
    lines.push(`complete -c omakit -n __fish_use_subcommand -a ${sub.name} -d ${single(sub.description)}`)
  }
  for (const sub of subcommands) {
    const when = `-n ${single(`__fish_seen_subcommand_from ${sub.name}`)}`
    if (sub.target) lines.push(`complete -c omakit ${when} -a '(__fish_complete_directories)'`)
    for (const { flag, value } of sub.flags) {
      const long = `-l ${flag.slice(2)}`
      if (value === "category") lines.push(`complete -c omakit ${when} ${long} -x -a ${single(categories.map(fishWord).join(" "))}`)
      else if (value === "tags") lines.push(`complete -c omakit ${when} ${long} -x -a ${single(tags.join(" "))}`)
      else if (value === "file") lines.push(`complete -c omakit ${when} ${long} -r`)
      else if (value === "text") lines.push(`complete -c omakit ${when} ${long} -x`)
      else lines.push(`complete -c omakit ${when} ${long}`)
    }
  }
  return `${lines.join("\n")}\n`
}

// --- where a shell loads it from --------------------------------------------

/**
 * Where the user's shell would load the script from, so `omakit setup` can say
 * how to install it and only when it is not there. bash-completion reads the
 * XDG data directory; fish reads its config directory; zsh has no user
 * directory of its own, and `~/.zfunc` is the convention, added to `fpath`.
 *
 * @param {NodeJS.ProcessEnv} env
 * @returns {{ shell: string, path: string, display: string, note: string|null } | null}
 */
export function completionInstall(env = process.env) {
  const shell = basename(env.SHELL || "")
  const home = env.HOME || ""
  if (!home || !COMPLETION_SHELLS.includes(shell)) return null
  const tilde = (dir) => withHomeAbbreviated(dir, env)
  if (shell === "bash") {
    const dir = join(env.XDG_DATA_HOME || join(home, ".local/share"), "bash-completion/completions")
    return { shell, path: join(dir, "omakit"), display: `${tilde(dir)}/omakit`, note: null }
  }
  if (shell === "fish") {
    const dir = join(env.XDG_CONFIG_HOME || join(home, ".config"), "fish/completions")
    return { shell, path: join(dir, "omakit.fish"), display: `${tilde(dir)}/omakit.fish`, note: null }
  }
  const dir = join(env.ZDOTDIR || home, ".zfunc")
  return { shell, path: join(dir, "_omakit"), display: `${tilde(dir)}/_omakit`, note: "with `fpath+=~/.zfunc` before `compinit` in your .zshrc" }
}

/**
 * Install the script where the shell in $SHELL loads it from, so a person
 * never has to know the path: `omakit setup` calls this. Idempotent: a script
 * that is already there and names the current pin is left alone; a missing
 * one, or one from another pin, is written. The only file this writes is
 * the completion script at the path `completionInstall` names, and
 * tests/unit/self-containment.test.mjs holds it to that.
 *
 * @param {{ contract: { categories: string[], tagLabels: string[] }, pin: string, env?: NodeJS.ProcessEnv }} options
 * @returns {{ state: "installed"|"updated"|"current"|"unsupported", shell: string|null, display: string|null, note: string|null }}
 */
export function installCompletion({ contract, pin, env = process.env }) {
  const target = completionInstall(env)
  if (!target) return { state: "unsupported", shell: basename(env.SHELL || "") || null, display: null, note: null }
  const script = renderCompletion(target.shell, { contract, pin })
  let existing = null
  try {
    existing = readFileSync(target.path, "utf8")
  } catch {
    existing = null
  }
  if (existing === script) return { state: "current", ...target }
  mkdirSync(dirname(target.path), { recursive: true })
  const completionFile = target.path
  writeFileSync(completionFile, script)
  return { state: existing === null ? "installed" : "updated", ...target }
}
